#ifndef MILESTRO_GAME_RETCODE_H
#define MILESTRO_GAME_RETCODE_H

#include <cstdint>

constexpr int64_t MILESTRO_API_RET_OK = 0;
constexpr int64_t MILESTRO_API_RET_UNEXPECTED_EXCEPTION = -11709394;
constexpr int64_t MILESTRO_API_RET_FAILED = -1;
constexpr int64_t MILESTRO_API_RET_GLYPH_NOTFOUND = -2;

#endif //MILESTRO_MILESTRO_GAME_RETCODE_H
