target_os = "linux"
target_cpu = "x64"
is_debug = false
is_official_build = true
cc = "gcc"
cxx = "g++"
skia_enable_tools = false
skia_enable_ganesh = false
skia_enable_graphite = false
skia_enable_pdf = false
skia_enable_skottie = false
skia_enable_svg = false
skia_enable_skparagraph = false
skia_enable_fontmgr_custom_empty = true
skia_use_fontconfig = false
skia_use_freetype = true
skia_use_system_freetype2 = false
skia_use_freetype_woff2 = true
skia_use_harfbuzz = true
skia_use_system_harfbuzz = false
skia_use_system_zlib = false
skia_use_system_libpng = false
skia_use_gl = false
skia_use_icu = false
skia_use_client_icu = true
skia_use_libjpeg_turbo_decode = false
skia_use_libjpeg_turbo_encode = false
skia_use_libwebp_decode = false
skia_use_libwebp_encode = false
skia_use_piex = false
skia_use_wuffs = false
skia_use_expat = false
skia_use_perfetto = false
skia_use_partition_alloc = false
