#ifndef MILESTRO_GAME_RETCODE_H
#define MILESTRO_GAME_RETCODE_H

#include <cstdint>

constexpr int64_t MILESTRO_API_RET_OK = 0;
constexpr int64_t MILESTRO_API_RET_UNEXPECTED_EXCEPTION = -11709394;
constexpr int64_t MILESTRO_API_RET_FAILED = -1;


constexpr int64_t MILESTRO_API_RET_BEATMAP_FAILED = MILESTRO_API_RET_FAILED;
constexpr int64_t MILESTRO_API_RET_BEATMAP_UNEXPECTED = MILESTRO_API_RET_UNEXPECTED_EXCEPTION;

constexpr int64_t MILESTRO_API_RET_COMPRESSING_FAILED = MILESTRO_API_RET_FAILED;
constexpr int64_t MILESTRO_API_RET_COMPRESSING_UNEXPECTED = MILESTRO_API_RET_UNEXPECTED_EXCEPTION;

constexpr int64_t MILESTRO_API_RET_FS_FAILED = MILESTRO_API_RET_FAILED;

constexpr int64_t MILESTRO_API_RET_IMAGE_UNPACK_ERROR = -1;
constexpr int64_t MILESTRO_API_RET_IMAGE_DECODE_ERROR = -2;

constexpr int64_t MILESTRO_API_RET_AUDIO_FAILED = -1;

constexpr int64_t MILESTRO_API_RET_AUDIO_MUA_PREVIEW_RANGE_ERROR = -1; // 预览时间段设定错误
constexpr int64_t MILESTRO_API_RET_AUDIO_MUA_ENCODER_ERROR = -2;       // OPUS编码器报错
constexpr int64_t MILESTRO_API_RET_AUDIO_MUA_DECODER_ERROR = -3;       // OPUS解码器报错
constexpr int64_t MILESTRO_API_RET_AUDIO_MUA_CRC_ERROR = -4;           // CRC校验错误
constexpr int64_t MILESTRO_API_RET_AUDIO_MUA_OPUS_ENCODE_ERROR = -5;   // OPUS编码错误
constexpr int64_t MILESTRO_API_RET_AUDIO_MUA_PAD_SN_ERROR = -6;        // 填充长度错误
constexpr int64_t MILESTRO_API_RET_AUDIO_MUA_OFFSET_TOO_BIG = -7;      // 编码偏移量过大无法还原
constexpr int64_t MILESTRO_API_RET_AUDIO_MUA_TOOL_ERROR = -8;          // 外部工具错误
constexpr int64_t MILESTRO_API_RET_AUDIO_MUA_PARA_ERR = -9;            // 传的参数有问题
constexpr int64_t MILESTRO_API_RET_AUDIO_MUA_INVALID_HANDLE = -10;     // 传入的HANDLE错误

constexpr int64_t MILESTRO_API_RET_AUDIO_MUA_PLAYER_IRRFILTER_COEFFICIENTS_ARGS_COUNT = -11;
constexpr int64_t MILESTRO_API_RET_AUDIO_MUA_PLAYER_AUDIO_SOURCE_NOT_READY = -12;

constexpr int64_t MILESTRO_API_RET_WINDOW_FAILED = -1;

#endif //MILESTRO_MILESTRO_GAME_RETCODE_H
